name: Run tests
on:
  push:
    branches: [master]
jobs:
  install-dependencies-and-run-tests:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install node dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:run

      - name: Generate report
        run: npm run test:generate-report

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: allure-report