name: Run tests
on:
  push:
    branches: [master]
jobs:
  install-dependencies-and-run-tests:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install node dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:run

      - name: Generate report
        run: npm run test:generate-report

      - name: Set artifact name with timestamp
        id: set-artifact-name
        run: |
          TIMESTAMP=$(date +'%Y-%m-%dT%H-%M-%S')
          echo "ARTIFACT_NAME=$TIMESTAMP-test-report" >> $GITHUB_ENV

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: allure-report